Создание и перемещение задач
Denis-sit/kanban pull request #1
Opened 2024-02-09 11:09 UTC by Denis-sit

Реализован функционал по добавлению новой задачи в Backlog и дальнейшее перемещение задачи в другие блоки состояния задачи

2024-02-09 12:09 UTC, tromario requested changes

2024-02-09 12:09 UTC, tromario commented on src/components/Select/Select.tsx
> +    <select name="select" onChange={onChange}>
Я бы в этом компоненте завел обработчик для выбора, в котором просто выше передашь `event.target.value`

2024-02-09 12:09 UTC, tromario commented on src/components/Select/Select.tsx
> +  console.log(filteredData, "select");
Лучше сразу уровень `debug` ставить

2024-02-09 12:09 UTC, tromario commented on src/components/Select/Select.tsx
> +  filteredData,
Лучше просто `data`, т.к селекту должно быть все равно, что ему отправят (фильтрованные или чистые данные)

2024-02-09 12:09 UTC, tromario commented on src/components/Select/Select.tsx
> +        <option key={filteredData[i].id}>{options.name}</option>
А почему бы ключ сразу не устанавливать из `options.id` ? Плюс `options` звучит как множественное число, лучше просто `option` или что-то другое

2024-02-09 12:09 UTC, tromario commented on src/App.tsx
> +            key={uuid()}
Такое себе. Лучше ID задавать в исходных данных и подставлять сюда

2024-02-11 09:15 UTC, Denis-sit commented on src/App.tsx
> +            key={uuid()}
Использовать item.title соответствующей доски для key. Думаю неплохой вариант, значение всегда уникально для каждой доски

2024-02-11 09:18 UTC, Denis-sit commented on src/components/Select/Select.tsx
> +  console.log(filteredData, "select");
Удалил не все выводы в консоль.

2024-02-11 09:27 UTC, Denis-sit commented on src/components/Select/Select.tsx
> +        <option key={filteredData[i].id}>{options.name}</option>
Согласен, это очевидное решение, не знаю почему я сделал именно так

2024-02-15 18:06 UTC, tromario requested changes

2024-02-15 18:06 UTC, tromario commented on src/App.tsx
> +  const [taskCounter, settaskCounter] = useState({
settaskCounter  -> setTaskCounter?

2024-02-15 18:06 UTC, tromario commented on src/App.tsx
> +    active: newData[0].issues.length,
Не могу поддержать такой способ обращения по индексу. Если у тебя исходные данные изменятся, то все полетит. Поэтому я советую вместо ключа title использовать id, они могут быть фиксированными

2024-02-15 18:06 UTC, tromario commented on src/App.tsx
> +  function updateData(bordTitle: string, value: IIssues, flag: string) {
Уф.. Как насчет перейти на 4 таба или пробела (вместо 2)? Глазам будет спокойнее смотреть
До:
<img width="630" alt="image" src="https://github.com/Denis-sit/kanban/assets/16851287/38ec150f-3dac-44b3-939d-e3475fef398e">
После:
<img width="691" alt="image" src="https://github.com/Denis-sit/kanban/assets/16851287/80ab21cd-1461-455f-8256-28fc0c4c4892">

2024-02-15 18:06 UTC, tromario commented on src/App.tsx
> +      } else if (item.title === bordTitle && flag === 'delete') {
Как на счет flag сделать enum?

2024-02-15 18:06 UTC, tromario commented on src/App.tsx
> +  function updateData(bordTitle: string, value: IIssues, flag: string) {
Ф-ю точно можно унести из компонента в utils

2024-02-15 18:06 UTC, tromario commented on src/components/Board/Board.tsx
> +  function handlerClickSubmit() {
Где-то const, где-то function. Почему такое разногласие?

2024-02-15 18:06 UTC, tromario commented on src/components/Board/Board.tsx
> +    setSubmitButton((prev) => !prev);
Чем у тебя отличается стейт buttonClick от submitButton?

2024-02-15 18:06 UTC, tromario commented on src/components/Board/Board.tsx
> +  const handleDelit = (task: IIssues): void => {
Очепятка. Ну это уже точно ИДЕ могла подсказать

2024-02-15 18:06 UTC, tromario commented on src/components/Board/Board.tsx
> +  const handleDelit = (task: IIssues): void => {
Также лучше добавить алерт на подтверждение удаления

2024-02-16 22:31 UTC, Denis-sit commented on src/App.tsx
> +  const [taskCounter, settaskCounter] = useState({
Опечатка, исправил.

2024-02-16 22:33 UTC, Denis-sit commented on src/App.tsx
> +    active: newData[0].issues.length,
Согласен, название доски может измениться. Добавлено свойство id для доски задач.

2024-02-16 22:53 UTC, Denis-sit commented on src/App.tsx
> +      } else if (item.title === bordTitle && flag === 'delete') {
Отличная идея. Добавил enum Action

2024-02-16 22:55 UTC, Denis-sit commented on src/components/Board/Board.tsx
> +  function handlerClickSubmit() {
Изначально использовал function только, потом перешел на стрелочные функции. Исправлю все на стрелочные ф-и

2024-02-16 23:05 UTC, Denis-sit commented on src/components/Board/Board.tsx
> +    setSubmitButton((prev) => !prev);
Получается, что ничем. Удалил код повторяющий одно и тоже действие.

2024-02-16 23:20 UTC, Denis-sit commented on src/components/Board/Board.tsx
> +  const handleDelit = (task: IIssues): void => {
Добавил подтверждение удаления.

2024-02-17 02:03 UTC, Denis-sit commented on src/components/Board/Board.tsx
> +    setSubmitButton((prev) => !prev);
Это было сделано для того чтобы отличать селект от инпута когда делаю кнопку неактивной. Логика переработана и лишнее состояние было удаленно.

2024-02-19 17:07 UTC, merged